### ISSUE TITLE
Support for Gradle Kotlin DSL

### ISSUE THREAD

**Issue by WtfJoke** [MeilCli/gradle-update-check-action#1]
Have you tried supporting gradle kotlin dsl? Eg. build.gradle.kts

## Feature description
I think it would be easy not to modify existing build.gradle/build.gradle.kts like here: https://github.com/MeilCli/gradle-update-check-action/blob/master/src/main.ts#L11 so your action wouldnt need to maintain gradle-versions-plugin. I could imagine this would be configurable to use the existing gradle-versions-plugin.

**Comment by MeilCli** [comment]
@WtfJoke 
`skip_plugin_dependency` option will be skip modify existing build.gradle, so I think you can use build.gradle.kts by using this option.

**Comment by WtfJoke** [comment]
Thank you, it worked 👍
