### ISSUE TITLE
alpha and beta updates - how to avoid?

### ISSUE THREAD

**Issue by hrossi** [MeilCli/gradle-update-check-action#240]
Hi there

The action is displaying some alpha and beta updates even using `revision: release`.

Is there any way to avoid it?

The following command are being executed:
`gradlew dependencyUpdates -Drevision=release -DoutputFormatter=json`

Output example:
```json
            {
                "group": "androidx.appcompat",
                "available": {
                    "release": "1.4.0-alpha01",
                    "milestone": null,
                    "integration": null
                },
                "version": "1.3.0",
                "projectUrl": "https://developer.android.com/jetpack/androidx/releases/appcompat#1.4.0-alpha01",
                "name": "appcompat"
            }
```

**Comment by MeilCli** [comment]
@hrossi Hi, i think you will face good result if using `skip_plugin_dependency` option.

This action is automatically added plugin dependency, but its option can stop it. Then add plugin dependency manually.
https://github.com/ben-manes/gradle-versions-plugin

And add define of custom task to select update channels.
https://github.com/ben-manes/gradle-versions-plugin#rejectversionsif-and-componentselection

After confirming that it works locally, maybe running expected at GitHub Actions.

**Comment by hrossi** [comment]
Hi @MeilCli.

Thanks for the quick response.

I'll try to do that. Thanks.
