### ISSUE TITLE
Add dependabot support for bumping actual dependency versions in separate PRs

### ISSUE THREAD

**Issue by jaredsburrows** [MeilCli/gradle-update-check-action#513]
Add dependabot support for bumping actual dependency versions in separate PRs

**Comment by MeilCli** [comment]
@jaredsburrows 
I couldn't imagine your suggested feature. Could you tell me its feature detail?

**Comment by jaredsburrows** [comment]
@dependabot does these types of PRs: https://github.com/jaredsburrows/open-quartz/pull/17.

Can we do something for all configuration dependencies?

**Comment by MeilCli** [comment]
@jaredsburrows 
This action is using https://github.com/ben-manes/gradle-versions-plugin, and its readme explains details like do checking all projects and configurations.
As really, I found those code. 
ref: https://github.com/ben-manes/gradle-versions-plugin/blob/a6e0b868992b8ba66cb1c4cfd210f214ad0bd790/gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdates.kt#L38-L39

So, I think you don't need something.

**Comment by MeilCli** [comment]
close by no response
